version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-nerdstore
    environment:
      RABBITMQ_DEFAULT_USER: "nerdstore"
      RABBITMQ_DEFAULT_PASS: "nerdstore"
    ports:
      - "5672:5672"
      - "15672:15672"

  sql-server:
    image: desenvolvedorio/nerdstore-sql-server:latest
    container_name: nerdstore-sql-server
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"

  web-mvc:
    image: desenvolvedorio/nerdstore-web-mvc-ecommerce:latest
    container_name: nerdstore-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
    ports:
      - "5001:5001"
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    depends_on:
      - api-catalog
      - api-identity
      - api-customer
      - api-bff-shopping

  api-identity:
    image: desenvolvedorio/nerdstore-api-identity:latest
    container_name: nerdstore-api-identity
    build:
      context: ../src
      dockerfile: ./services/NSE.Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:7241
    depends_on:
      - rabbitmq
      - sql-server

  api-cart:
    image: desenvolvedorio/nerdstore-api-cart:latest
    container_name: nerdstore-api-cart
    build:
      context: ../src
      dockerfile: ./services/NSE.Cart.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:7136
    depends_on:
      - rabbitmq
      - api-identity
      - sql-server

  api-catalog:
    image: desenvolvedorio/nerdstore-api-catalog:latest
    container_name: nerdstore-api-catalog
    build:
      context: ../src
      dockerfile: ./services/NSE.Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:7012
    depends_on:
      - rabbitmq
      - sql-server

  api-customer:
    image: desenvolvedorio/nerdstore-api-customer:latest
    container_name: nerdstore-api-customer
    build:
      context: ../src
      dockerfile: ./services/NSE.customers.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:7057
    depends_on:
      - rabbitmq
      - api-identity
      - sql-server

  api-order:
    image: desenvolvedorio/nerdstore-api-order:latest
    container_name: nerdstore-api-order
    build:
      context: ../src
      dockerfile: ./services/NSE.orders.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:7283
    depends_on:
      - rabbitmq
      - api-identity
      - sql-server

  api-payment:
    image: desenvolvedorio/nerdstore-api-payment:latest
    container_name: nerdstore-api-payment
    build:
      context: ../src
      dockerfile: ./services/NSE.payment.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:7100
    depends_on:
      - rabbitmq
      - api-identity
      - sql-server
      - api-order

  api-bff-shopping:
    image: desenvolvedorio/nerdstore-api-bff-shopping:latest
    container_name: nerdstore-api-bff-shopping
    build:
      context: ../src
      dockerfile: ./api gateways/NSE.Bff.Shopping/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:7213
    depends_on:
      - rabbitmq
      - api-identity
      - api-cart
      - api-payment
      - api-order

  nerdstore-server:
    image: desenvolvedorio/nerdstore-server:latest
    container_name: nerdstore-server
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-mvc